# Forecastbase Example Config
# Created by Mutlu Polatcan
# 01.02.2018

################################### REQUIRED ATTRIBUTES #####################################
prescient.dataset.filepath: "../datasets/energy-demand-forecasting/zone_1_energy_demand.csv"

prescient.training.data.percent.min: 70
prescient.training.data.percent.max: 80
prescient.training.data.percent.increment.by: 5

prescient.interval.width.min: 0.05
prescient.interval.width.max: 0.85
prescient.interval.width.increment.by: 0.05

prescient.changepoint.prior.scale.min: 0.001
prescient.changepoint.prior.scale.max: 0.5
prescient.changepoint.prior.scale.increment.by: 0.001

prescient.predict.next: 7
prescient.predict.freq: "D"

prescient.convergence.detection.acr.threshold: -0.5 # must be negative
prescient.convergence.detection.measure.number: 3

prescient.paralellism: 3
prescient.holiday.weekends.enabled: true

################################### OPTIONAL ATTRIBUTES #######################################
prescient.holiday.special.days:
  # - "2017-01-30"
  # - "2017-02-28"
###############################################################################################